language: minimal
sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.23.2

before_install:
   - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
   - chmod +x docker-compose
   - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose up -d postgres

before_script:
  - ./prepare_db.sh

script:
  - docker-compose run app make test

branches:
  only:
  - master

notifications:
  irc:
    channels:
      - "chat.freenode.net#emfcamp-web"
    on_success: change
    on_failure: always
