version: "3.7"
services:
  app:
    build:
      context: "./"
    networks:
      - emfweb
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: 'make run'

  postgres:
    image: 'mdillon/postgis:10'
    networks:
      - emfweb

networks:
  emfweb:
